/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponzoriRouteImport } from './routes/sponzori'
import { Route as SluzbyRouteImport } from './routes/sluzby'
import { Route as ProjektyRouteImport } from './routes/projekty'
import { Route as PribehRouteImport } from './routes/pribeh'
import { Route as PoznejteMeRouteImport } from './routes/poznejte-me'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as DopisySkafandrRouteImport } from './routes/dopisy-skafandr'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'

const SponzoriRoute = SponzoriRouteImport.update({
  id: '/sponzori',
  path: '/sponzori',
  getParentRoute: () => rootRouteImport,
} as any)
const SluzbyRoute = SluzbyRouteImport.update({
  id: '/sluzby',
  path: '/sluzby',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektyRoute = ProjektyRouteImport.update({
  id: '/projekty',
  path: '/projekty',
  getParentRoute: () => rootRouteImport,
} as any)
const PribehRoute = PribehRouteImport.update({
  id: '/pribeh',
  path: '/pribeh',
  getParentRoute: () => rootRouteImport,
} as any)
const PoznejteMeRoute = PoznejteMeRouteImport.update({
  id: '/poznejte-me',
  path: '/poznejte-me',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const DopisySkafandrRoute = DopisySkafandrRouteImport.update({
  id: '/dopisy-skafandr',
  path: '/dopisy-skafandr',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/dopisy-skafandr': typeof DopisySkafandrRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/poznejte-me': typeof PoznejteMeRoute
  '/pribeh': typeof PribehRoute
  '/projekty': typeof ProjektyRoute
  '/sluzby': typeof SluzbyRoute
  '/sponzori': typeof SponzoriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/dopisy-skafandr': typeof DopisySkafandrRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/poznejte-me': typeof PoznejteMeRoute
  '/pribeh': typeof PribehRoute
  '/projekty': typeof ProjektyRoute
  '/sluzby': typeof SluzbyRoute
  '/sponzori': typeof SponzoriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/dopisy-skafandr': typeof DopisySkafandrRoute
  '/kontakt': typeof KontaktRoute
  '/legal': typeof LegalRoute
  '/poznejte-me': typeof PoznejteMeRoute
  '/pribeh': typeof PribehRoute
  '/projekty': typeof ProjektyRoute
  '/sluzby': typeof SluzbyRoute
  '/sponzori': typeof SponzoriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/dopisy-skafandr'
    | '/kontakt'
    | '/legal'
    | '/poznejte-me'
    | '/pribeh'
    | '/projekty'
    | '/sluzby'
    | '/sponzori'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/dopisy-skafandr'
    | '/kontakt'
    | '/legal'
    | '/poznejte-me'
    | '/pribeh'
    | '/projekty'
    | '/sluzby'
    | '/sponzori'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/dopisy-skafandr'
    | '/kontakt'
    | '/legal'
    | '/poznejte-me'
    | '/pribeh'
    | '/projekty'
    | '/sluzby'
    | '/sponzori'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  DopisySkafandrRoute: typeof DopisySkafandrRoute
  KontaktRoute: typeof KontaktRoute
  LegalRoute: typeof LegalRoute
  PoznejteMeRoute: typeof PoznejteMeRoute
  PribehRoute: typeof PribehRoute
  ProjektyRoute: typeof ProjektyRoute
  SluzbyRoute: typeof SluzbyRoute
  SponzoriRoute: typeof SponzoriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponzori': {
      id: '/sponzori'
      path: '/sponzori'
      fullPath: '/sponzori'
      preLoaderRoute: typeof SponzoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sluzby': {
      id: '/sluzby'
      path: '/sluzby'
      fullPath: '/sluzby'
      preLoaderRoute: typeof SluzbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty': {
      id: '/projekty'
      path: '/projekty'
      fullPath: '/projekty'
      preLoaderRoute: typeof ProjektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pribeh': {
      id: '/pribeh'
      path: '/pribeh'
      fullPath: '/pribeh'
      preLoaderRoute: typeof PribehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poznejte-me': {
      id: '/poznejte-me'
      path: '/poznejte-me'
      fullPath: '/poznejte-me'
      preLoaderRoute: typeof PoznejteMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dopisy-skafandr': {
      id: '/dopisy-skafandr'
      path: '/dopisy-skafandr'
      fullPath: '/dopisy-skafandr'
      preLoaderRoute: typeof DopisySkafandrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  DopisySkafandrRoute: DopisySkafandrRoute,
  KontaktRoute: KontaktRoute,
  LegalRoute: LegalRoute,
  PoznejteMeRoute: PoznejteMeRoute,
  PribehRoute: PribehRoute,
  ProjektyRoute: ProjektyRoute,
  SluzbyRoute: SluzbyRoute,
  SponzoriRoute: SponzoriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
